Add support for BGP4MP add-path encoded MRT Updates.
CAIDA/libparsebgp pull request #85
Opened 2021-02-17 08:31 UTC by dteach-rv

This PR extends  previous work to implement correct parsing of RFC 8050 add-path encoded NLRI in libparsebgp.  Specifically we're adding support for BGP4MP updates with add-path encoded NLRI.

2021-02-17 18:15 UTC, dteach-rv commented
Rebased off of master.

2021-02-17 18:35 UTC, alistairking requested changes
minor nits, but otherwise this looks great!

2021-02-17 18:35 UTC, alistairking commented on lib/bgp/parsebgp_bgp_open.h
>    // TODO: add ADD-PATH capability
guess this can be removed :)

2021-02-17 18:35 UTC, alistairking commented on lib/bgp/parsebgp_bgp_open.h
> +
whitespace

2021-02-17 18:35 UTC, alistairking commented on lib/bgp/parsebgp_bgp_opts.h
> +
whitespace

2021-02-17 18:35 UTC, alistairking commented on lib/bgp/parsebgp_bgp_update.c
> +    tuple->addl_path_id = 0;
this gets zeroed in the `else` case just below.

2021-02-17 18:35 UTC, alistairking commented on lib/bgp/parsebgp_bgp_update_mp_reach.c
> +    tuple->addl_path_id = 0;
perhaps move to an else block like you did above?

2021-02-17 18:49 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_open.h
> +
I added a comment above the send_recieve.  Otherwise, this seems to follow the existing formatting.  e.g.
```C
typedef struct parsebgp_bgp_open_capability_mpbgp {

  /** AFI */
  uint16_t afi;

  /** Reserved (always 0) */
  uint8_t reserved;

  /** SAFI */
  uint8_t safi;

} parsebgp_bgp_open_capability_mpbgp_t;
```

2021-02-17 18:54 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_open.h
> +
I see which whitespace you're referring to now.

2021-02-17 19:14 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_update.c
> +    tuple->addl_path_id = 0;
Removing the initialization value, throws a warning at compile.  So I'll keep the initialization value and remove the else.

2021-02-17 19:14 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_update_mp_reach.c
> +    tuple->addl_path_id = 0;
same as above.

2021-02-17 19:31 UTC, kenkeys commented on lib/mrt/parsebgp_mrt.c
> +  buf += slen;
This block used to apply only to the MESSAGE* subtypes, but by pulling it out of the switch it now also incorrectly applies to the STATE_CHANGE* subtypes.  I suggest splitting the switch into two switches: the first to set `opts->bgp` flags for the various MESSAGE* subtypes; and the second to do the decoding, with one block for all the STATE_CHANGE* and one block for all the MESSAGE*.

2021-02-17 19:39 UTC, kenkeys requested changes

2021-02-17 19:39 UTC, kenkeys commented on lib/mrt/parsebgp_mrt.c
> +  buf += slen;
This block used to apply only to the MESSAGE* subtypes, but by pulling it out of the switch it now also incorrectly applies to the STATE_CHANGE* subtypes.  I suggest splitting the switch into two switches: the first to set `opts->bgp` flags for the various MESSAGE* subtypes; and the second to do the decoding, with one block for all the STATE_CHANGE* and one block for all the MESSAGE*.

2021-02-19 00:34 UTC, dteach-rv commented on lib/mrt/parsebgp_mrt.c
> +  buf += slen;
I went ahead and made those changes. LMK if that looks sane.

2021-02-19 20:16 UTC, kenkeys submitted a review, later dismissed

2021-02-20 00:42 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_open.h
> +
Fixed.

2021-02-20 00:42 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_opts.h
> +
Fixed.

2021-02-20 00:43 UTC, dteach-rv commented on lib/bgp/parsebgp_bgp_update_mp_reach.c
> +    tuple->addl_path_id = 0;
Fixed.

2021-02-20 00:43 UTC, dteach-rv commented on lib/mrt/parsebgp_mrt.c
> +  buf += slen;
Fixed.

2021-02-20 00:59 UTC, alistairking requested changes

2021-02-20 00:59 UTC, alistairking commented on lib/mrt/parsebgp_mrt.c
> +    fprintf(stderr, "entering parsebgp_decode_ext\n");
this can be removed ;)

2021-02-20 01:08 UTC, dteach-rv commented on lib/mrt/parsebgp_mrt.c
> +    fprintf(stderr, "entering parsebgp_decode_ext\n");
shoot. Yep.

2021-02-20 01:12 UTC, dteach-rv commented on lib/mrt/parsebgp_mrt.c
> +    fprintf(stderr, "entering parsebgp_decode_ext\n");
Working on too many things at once.  Should be fixed now.

2021-02-20 02:22 UTC, alistairking approved these changes

2021-02-20 05:36 UTC, merged